import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/css/tailwind.css'
import { ThemeProvider } from 'next-themes'
import Header from '@/components/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <link rel="icon" type="image/png" sizes="32x32" href={`/public/icon-32x32.png`} />
      <link rel="icon" type="image/png" sizes="16x16" href={`/public/icon-16x16.png`} />
      <meta name="msapplication-TileColor" content="#000000" />
      <body className="bg-white pl-[calc(100vw-100%)] text-black antialiased dark:bg-gray-950 dark:text-white">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
          <ThemeProvider attribute="class" enableSystem>
            <Header />
            <main className="mb-auto">{children}</main>
          </ThemeProvider>
        </div>
      </body>
    </html>
  )
}
